AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS VPC Delete project role template'

Parameters:
  FoundationAccountID:
    Description: 'Foundation Account ID'
    Type: String
    Default: '__FOUNDATION_AUTOMATION_ACCOUNT_ID__'
    MinLength: 12
    MaxLength: 12

Resources:
  AwsVpcDeleteProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AwsVpcDeleteProjectRole
      MaxSessionDuration: 3600
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${FoundationAccountID}:root'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Allow_VPC_Delete
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DeleteSubnet
                  - ec2:DeleteInternetGateway
                  - ec2:DetachInternetGateway
                  - ec2:DeleteVpc
                Resource:
                  - !Sub 'arn:aws:ec2:*:${AWS::AccountId}:vpc/*'
                  - !Sub 'arn:aws:ec2:*:${AWS::AccountId}:internet-gateway/*'
                  - !Sub 'arn:aws:ec2:*:${AWS::AccountId}:subnet/*'
              - Effect: Allow
                Action:
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeVpcs
                  - ec2:DescribeRegions
                  - ec2:DescribeSubnets
                Resource: '*'
