AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS VPC Delete Organization role template'

Parameters:
  FoundationAccountID:
    Description: 'Foundation Account ID'
    Type: String
    Default: '__FOUNDATION_AUTOMATION_ACCOUNT_ID__'
    MinLength: 12
    MaxLength: 12

Resources:
  AwsVpcDeleteOrgaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AwsVpcDeleteOrgaRole
      MaxSessionDuration: 3600
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${FoundationAccountID}:root'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Allow_Org_Account_list
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - organizations:DescribeAccount
                Resource: '*'
